# Generated by Django 4.2.5 on 2023-09-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
